name: RandomSpawnPlus5
version: '${version}'
main: systems.kscott.randomspawnplus.Randomspawnplus
api-version: 1.19
authors: [ 89apt89, Dreeam ]
description: A comprehensive random spawning plugin for modern Minecraft versions.
