name: RandomSpawnPlus
version: ${version}
main: systems.kscott.randomspawnplus.RandomSpawnPlus
api-version: 1.13
folia-supported: true
softdepend:
  - Essentials
  - Vault
  - LuckPerms
authors:
  - 89apt89
  - Dreeam-qwq
description: A comprehensive random spawning plugin for modern Minecraft versions.

commands:
  wild:
    description: Get a wild spawn
    usage: /wild [player]
  rsp:
    description: Main plugin command
    usage: /rsp

permissions:
  rsp.randomspawn:
    description: Enable random spawns
    default: op
  rsp.wild:
    description: Teleport to a random location
    default: op
  rsp.wild.others:
    description: Teleport others to a random location
    default: op
  rsp.wild.bypasscooldown:
    description: Bypass the teleport cooldown
    default: op
  rsp.wild.bypasscost:
    description: Bypass the /wild cost
    default: op
  rsp.manage:
    description: Access to the /rsp (and /rsp reload) command
    default: op
