name: Buils RandomSpawnPlus

on: [ push ]

jobs:
  build:
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 17
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build
      - name: Upload RandomSpawnPlus5
        uses: actions/upload-artifact@v3
        with:
          name: RandomSpawnPlus5
          path: build/libs
