name: Build RandomSpawnPlus

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "github.actor != 'dependabot[bot]'"
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: zulu

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew clean build

#      - name: Release RandomSpawnPlus
#        if: github.event_name != 'pull_request'
#        uses: marvinpinto/action-automatic-releases@master
#        with:
#          title: "RandomSpawnPlus"
#          automatic_release_tag: "6.0.0-SNAPSHOT"
#          repo_token: "${{ secrets.GITHUB_TOKEN }}"
#          files: "Common/build/libs/*.jar"
#          prerelease: true
