name: Build RandomSpawnPlus5 - Maven

on: [ push ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: "!contains(github.event.commits[0].message, '[ci-skip]')"
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Upload RandomSpawnPlus5
        uses: actions/upload-artifact@v3
        with:
          name: RandomSpawnPlus5-maven
          path: target/
